version: "3.3"
services:
  redis:
    image: redis:alpine
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      mode: replicated
  web:
    image: vm1:5000/stackdemo
    ports:
      - "8000:8000"
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      mode: replicated
